{% set name = "outcome" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e862f01d4e626e63e8f92c38d1f8d5546d3f9cce989263c521b2e7990d186967

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - attrs
  run:
    - python
    - attrs

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/python-trio/outcome
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Capture the outcome of Python function calls
  description: Capture the outcome of Python function calls.
